#!/usr/bin/env python3
"""Phase 1: checksums + manifest updates for output_archives/<run_id>/."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

CANONICAL_APK_ROOT = "/mnt/Files/FromLaptop/thesis_full_dataset"


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _rel(path: Path, base: Path) -> str:
    try:
        return str(path.relative_to(base))
    except ValueError:
        return str(path)


def finalize_archive(
    run_id: str,
    *,
    apk_root: str | None = None,
) -> Path:
    archive = ROOT / "output_archives" / run_id
    if not archive.is_dir():
        raise FileNotFoundError(f"Archive not found: {archive}")

    artifacts = ROOT / "artifacts"
    entries: list[tuple[str, Path]] = []

    def add(label: str, path: Path) -> None:
        if path.is_file():
            entries.append((label, path))

    add("processed_features", artifacts / "processed" / "dex_header_features.pt")
    add("checkpoint", artifacts / "checkpoints" / "latest_checkpoint.pth")
    add("normalization", artifacts / "normalization.json")

    metrics_dir = artifacts / "metrics"
    for name in (
        "epochs.jsonl",
        "metrics_val.json",
        "preprocess_summary.json",
        "training_run_info.json",
        "checkpoint_summary.json",
        "corpus_stats.json",
    ):
        add(f"metrics/{name}", metrics_dir / name)

    for name in (
        "metrics/metrics_val.json",
        "metrics/epochs.jsonl",
        "metrics/preprocess_summary.json",
        "metrics/training_run_info.json",
        "metrics/checkpoint_summary.json",
        "metrics/normalization.json",
        "logs/pipeline_full.log",
        "config/default.yaml.snapshot",
        "corpus_stats/label_distribution.json",
        "corpus_stats/dex_file_counts.json",
        "corpus_stats/year_folder_counts.json",
    ):
        add(f"archive/{name}", archive / name)

    manifest_path = archive / "RUN_MANIFEST.json"
    manifest: dict = {}
    if manifest_path.is_file():
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))

    manifest["canonical_apk_root"] = apk_root or CANONICAL_APK_ROOT
    if manifest.get("apk_root") != manifest["canonical_apk_root"]:
        manifest["apk_root_at_train_time"] = manifest.get("apk_root")
    manifest["apk_root"] = manifest["canonical_apk_root"]
    manifest["verify_checksums"] = (
        f"cd {ROOT} && sha256sum -c output_archives/{run_id}/RUN_MANIFEST.sha256"
    )

    (archive / "figures").mkdir(exist_ok=True)
    (archive / "export").mkdir(exist_ok=True)
    (archive / "parity").mkdir(exist_ok=True)

    for sub, text in (
        (
            "figures",
            "# Figures (Phase 2)\n\nGenerated by `scripts/plot_bm1_results.py`.\n",
        ),
        (
            "export",
            "# ONNX export (Phase 3)\n\nPopulated by `scripts/export_onnx.py`.\n",
        ),
        (
            "parity",
            "# Parity (Phase 4)\n\nPopulated by `scripts/parity_check_onnx.py`.\n",
        ),
    ):
        readme = archive / sub / "README.md"
        if not readme.is_file():
            readme.write_text(text, encoding="utf-8")

    lines: list[str] = []
    index: dict[str, dict[str, str]] = {}
    for label, path in entries:
        digest = _sha256(path)
        rel_repo = _rel(path, ROOT)
        lines.append(f"{digest}  {rel_repo}")
        index[label] = {"path": rel_repo, "sha256": digest}

    manifest["archive_phase1"] = {
        "completed_at": datetime.now(timezone.utc).isoformat(),
        "checksum_file": "RUN_MANIFEST.sha256",
        "artifact_index": index,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    # Hash manifest after final write (not included in artifact_index loop above for stability)
    manifest_rel = _rel(manifest_path, ROOT)
    lines.append(f"{_sha256(manifest_path)}  {manifest_rel}")

    checksum_path = archive / "RUN_MANIFEST.sha256"
    checksum_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    latest = ROOT / "output_archives" / "LATEST_RUN.txt"
    latest.write_text(run_id + "\n", encoding="utf-8")

    return checksum_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Finalize BM1 output_archives run.")
    parser.add_argument("--run-id", type=str, required=True)
    parser.add_argument(
        "--apk-root",
        type=str,
        default=CANONICAL_APK_ROOT,
        help="Canonical dataset path for manifest",
    )
    args = parser.parse_args(argv)

    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))

    out = finalize_archive(args.run_id, apk_root=args.apk_root)
    print(f"Wrote {out}")
    print(f"Updated {ROOT / 'output_archives' / args.run_id / 'RUN_MANIFEST.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
